##------------------------------------------------------------------
##------SERVER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
server:
  port: 8080
spring:
  application:
    name: gateway-api
  security:
    user:
      name: admin
      password: 12341234

##------------------------------------------------------------------
##------GATEWAY API CONFIGURATION-----------------------------------
##------------------------------------------------------------------
eureka:
  instance:
    hostname: sr-api-gateway-service
  client:
    register-with-eureka: false # client disabled
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url: #url to be used by services that want to register with eureka server (Gateway API)
      defaultZone: http://admin:12341234@${eureka.instance.hostname}:${server.port}/eureka



##------------------------------------------------------------------
##------ZUUL ROUTING CONFIGURATION----------------------------------
##------------------------------------------------------------------
zuul:
  routes:
    user-service:
      path: /user-service/**
    property-service:
      path: /property-service/**
    renter-service:
      path: /renter-service/**

##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    name: logs/gateway-api.log
    max-size: 10MB
  level:
    com.mg: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot: ERROR
    zipkin2.reporter.AsyncReporter: ERROR